module.exports = {
    DOCUMENT_INSERT:         "DOCUMENT_INSERT",
    DOCUMENT_REMOVE:         "DOCUMENT_REMOVE",
    ERROR_THROW:             "ERROR_THROW",
    ERROR_CLEAR:             "ERROR_CLEAR",
    UPLOADING_FILE_INIT:     "UPLOADING_FILE_INIT",
    UPLOADING_FILE_PROGRESS: "UPLOADING_FILE_PROGRESS",
    UPLOADING_FILE_END:      "UPLOADING_FILE_END",
    USER_INSERT:             "USER_INSERT",
    USER_REMOVE:             "USER_REMOVE"
};
